---
- name: Database server
  hosts: database_server
  roles:
  - common
  - mariadb
  - wordpress
  
- name: Web servers
  hosts: web_servers
  roles:
  - common
  - apache2
  - postfix
  - proftpd
  - filestorage
  - wordpress

